services:
  app:
    build:
      # Use the Dockerfile in the .devcontainer directory
      context: .
      dockerfile: Dockerfile

    volumes:
      # Mount your project folder into the container
      - ..:/workspaces/rsvp-priority:cached

    # Keep the container running for you to connect to
    command: sleep infinity