{
  "name": "RSVP App (Docker Compose)",
  "dockerComposeFile": "docker-compose.yml",
  "service": "app",
  "workspaceFolder": "/workspaces/rsvp-priority",
  "forwardPorts": [5000],

  "portAttributes": {
    "5000": {
      "label": "Flask App",
      "onAutoForward": "openPreview",
      "visibility": "public"
    }
  },

  "features": {
    "ghcr.io/devcontainers/features/docker-in-docker:2": {}
  },
  "postCreateCommand": "echo 'Codespace is ready!'"
}